### ISSUE TITLE
new location_subfolder variable?

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ansible-playbook#106]
In case you think this might be a useful feature...

To host a Plone site from a domain folder, e.g. https://demo.plone.io/backend, I added these commits in the plone.io branch https://github.com/plone/ansible-playbook/tree/plone.io : 

- https://github.com/plone/ansible-playbook/commit/abe49fe887bcc8a1e26cdb635e553973ae4740a6
- https://github.com/plone/ansible-playbook/commit/e01aa9ebaca9ee9cd659d2104d7154e54e5347db

then all I had to do was specify `location_subfolder: backend`

**Comment by smcmahon** [comment]
Nice! Merged.
