### ISSUE TITLE
best way to reuse this playbook?

### ISSUE THREAD

**Issue by davisagli** [plone/ansible-playbook#11]
What's the best way to use this playbook to deploy multiple sites? I know I can have a separate fork checked out for each site, but that feels hard to maintain. Is there a way I can have my site-specific configuration in a .yml file in the site's repository and have it say "run the playbook from plone/ansible-playbook (or a central installation of it on my computer) with this configuration"?

**Comment by davisagli** [comment]
I ended up copying configure.yml and playbook.yml into my client's repository, as well as creating local-configure.yml there. I then created ansible.cfg in the same directory with these contents to make ansible look in my central copy of ansible-playbook for the roles:

```
[defaults]
roles_path = /Users/davisagli/Work/ansible-playbook/roles
```

It'd be nice if there was a way to do this without duplicating configure.yml and playbook.yml though.

**Comment by davisagli** [comment]
Hmm, I also have to copy in templates/motd.j2 or remove the task that sets up the motd. It would be nice if this task was also done in a role so that I don't have to copy it.

**Comment by djowett** [comment]
I'm having the same thoughts, but perhaps this helps (from [Ansible playbook variables](http://docs.ansible.com/ansible/playbooks_variables.html#passing-variables-on-the-command-line))
> As of Ansible 1.3, extra vars can be loaded from a JSON file with the @ syntax:
> --extra-vars "@some_file.json"

**Comment by smcmahon** [comment]
My way of handling multiple hosts: use a [host_vars](http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data) directory and skip the local_configure.yml file.

**Comment by djowett** [comment]
@smcmahon so I take it in that instance you move configure.yml under group_vars/all/ to keep default variables working?

**Comment by smcmahon** [comment]
I don't think anything reads configure.yml any longer.

**Comment by djowett** [comment]
ah I was looking at 1.1
