### ISSUE TITLE
requirements.yml claims for ansible.plone_server.git version: 1.3.7 while only 1.3.6 is available

### ISSUE THREAD

**Issue by acsr** [plone/ansible-playbook#121]
When running ansible-playbook version 1.3.7 with ansible 2.8.5 and vagrant 2.2.5 on MacOS 10.13.6 you may get the error:

````
[WARNING]: - plone.plone_server was NOT installed successfully: - command git checkout 1.3.7 failed in
directory /tmp/tmpsvtPtq (rc=1)
````

For me changing the version for in ansible.plone_server in requirements.yml 

````
- src: https://github.com/plone/ansible.plone_server.git
  version: 1.3.6
  name: plone.plone_server
````

did the job to fix the issue, since the official version in the https://github.com/plone/ansible.plone_server.git is currently still 1.3.6.

**Comment by smcmahon** [comment]
I had failed to push the current tag in the ansible.plone_server repo. Fixed.

Thanks!
