### ISSUE TITLE
Allow Bearer JWT token auth in Varnish for plone.restapi

### ISSUE THREAD

**Issue by fulv** [plone/ansible-playbook#127]
The varnish setting `proxy_cache_block_basic_auth` completely blocks the Authorization header to prevent login at the Zope root level.
However, this has the negative side-effect of also blocking this header when the `Bearer` scheme is used (instead of `Basic`) which is required by plone.restapi when a JWT token is used to authenticate.

I am going to submit a PR with a simple fix.

**Comment by stevepiercy** [comment]
Closed by #129
