### ISSUE TITLE
Problems at 'Run buildout' task

### ISSUE THREAD

**Issue by HammelH** [plone/ansible-playbook#145]
I tried to install Plone via Ansible on Debian buster, but it always hang up at the 'Run buildout' task without an error message:

```
TASK [plone.plone_server : Run buildout - output goes to /usr/local/plone-5.2/zeoserver/buildout.log] ******************************************************************************************
task path: /opt/ansible-playbook/roles/plone.plone_server/tasks/main.yml:274
Using module file /usr/lib/python3/dist-packages/ansible/modules/commands/command.py
<vm-debian-plone> ESTABLISH SSH CONNECTION FOR USER: foo
<vm-debian-plone> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<vm-debian-plone> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=foo)
<vm-debian-plone> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<vm-debian-plone> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/root/.ansible/cp/bcb057b34f)
<vm-debian-plone> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=foo -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/bcb057b34f vm-debian-plone '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=123123123123123123] password: " -u plone_buildout /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-123123123123123123; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
```
_I changed username and key (not sure if this is a kind of secret) of output above._

/usr/local/plone-5.2/zeoserver/buildout.log is empty

The 'Download buildout cache if needed' task failed a bit earlier, because it cannot find the file on the web server. I am not sure whether this can be ignored:
```
TASK [plone.plone_server : Download buildout cache if needed] **********************************************************************************************************************************
fatal: [vm-debian-plone]: FAILED! => {"changed": false, "msg": "Failure downloading https://launchpad.net/plone/5.2/5.2.1/+download/buildout-cache.tar.bz2, HTTP Error 404: Not Found"}
...ignoring
```

**Comment by fredvd** [comment]
It seems the buildout-cache.tar.bz2 is no longer generated and/or uploaded to launchpad. For Plone releases. The last release containing one is Plone release 5.1.6 released at the end of 2019.  (5.1.7 is the 'last' update release in the 5.1 series as the most recent version is maintained (5.2.X).

I'm not sure if this is an omission, or if other processes requiring a convenience archive to avoid downloading individual eggs, like our CI/CD integrations nowadays download the UnifiedInstaller and extract the eggs from that package. 

Please note we are having some issues with getting the UnifiedInstaller stable for Plone 5.2.3, so that the download is missing there is a known situation.

@mauritsvanrees @esteele?

**Comment by HammelH** [comment]
OK, but is the missing buildout-cache cause of the main problem? I thought build with downloaded cache could just decrease the whole build time. But in my case it seems that the build process won't start, otherwise buildout.log wouldn't be empty. Is that also a known problem or is there anything I did wrong?
I used a fresh Debian Buster installation for Plone and Ansible 2.7.7.

**Comment by HammelH** [comment]
I tried it with a newer Version of Ansible (2.9.16) and now it works.

**Comment by tkimnguyen** [comment]
@HammelH to answer your question: the buildout-cache isn't necessary for recent builds of the unified installer, so it should be handling it correctly.
