### ISSUE TITLE
postfix does not relay mail to the domain being hosted

### ISSUE THREAD

**Issue by davisagli** [plone/ansible-playbook#15]
The postfix configuration includes `{{ inventory_hostname }}` in the `mydestination` setting. This means that postfix considers itself to be the intended recipient of mail at the domain being hosted via HTTP, even though the domain's MX record probably points elsewhere. Is there a reason this is included in mydestination?

**Comment by davisagli** [comment]
I guess another solution might be to use www.[domain] as the hostname in my inventory instead of just the bare domain.

**Comment by smcmahon** [comment]
I can't really imagine a situation in which the inventory_hostname value isn't a local destination.
