### ISSUE TITLE
Varnish 4 and handling missing python 2.x

### ISSUE THREAD

**Issue by fulv** [plone/ansible-playbook#16]
There are a few issues when deploying to Ubuntu 15.04:

* The main one is that it does not come with python 2.x installed;
* It has varnish 4, so the syntax of the vcl file needs to change
* There is a file `/etc/fail2ban/jail.d/defaults-debian.conf` with just a single section for `[sshd]`, with a single line: `enabled = true` that causes fail2ban to break.

The first issue can be solved with a `-m raw` command before doing the deployment.

For the last one, I don't really have a solution, other than commenting out (or deleting the whole file) and re-deploying again.

I have a branch with my suggested changes, and I'll open a PR.  I'm not sure how different OS versions should be dealt with.

**Comment by davisagli** [comment]
I think it makes sense to primarily target the latest LTS Ubuntu release (currently 14.04) since they are supported for 5 years whereas the other releases are only supported for 9 months. The next LTS release is anticipated in April 2016.

**Comment by fulv** [comment]
I think the list I made above can be unpacked and separated from OS version considerations:

* do we want to target varnish 4, instead of 3?
* add a step in the readme for a `-m raw` command in case the OS does not have python 2.x installed, since ansible still does not support python 3 completely.

**Comment by nomadhacker** [comment]
Agree.  Benefits of Ansible are abstracting away the OS wherever possible.

**Comment by smcmahon** [comment]
I'm OK with allowing 15.04 as long as we don't break 14.04. My primary production target is probably always going to be the latest LTS (so long as Ubuntu keeps doing a reasonable job with them).

**Comment by smcmahon** [comment]
Recent updates add VCL 4 and use it automatically for 15.08 and jessie
