### ISSUE TITLE
Support selinux

### ISSUE THREAD

**Issue by jpgimenez** [plone/ansible-playbook#32]
Currently deploying to a selinux enabled server works but you end up with a non working installation, nginx can't connect to varnish, and haproxy can't connect to plone instances, so you only get 50x responses from nginx.

**Comment by smcmahon** [comment]
jpgimenez, can you tell me if we've got this fixed?

**Comment by smcmahon** [comment]
Sorry, I should have been more clear. I was asking if it's already fixed:

https://github.com/plone/ansible-playbook/commit/7b5a68ea907d6dc43c1a1932d7c5fdca58a16f7c

I didn't find anything that was needed to make varnish work.

**Comment by smcmahon** [comment]
Please re-open if this isn't fixed.
