### ISSUE TITLE
Webserver extras overridden when trying to set auth_basic

### ISSUE THREAD

**Issue by djowett** [plone/ansible-playbook#35]
I've wanted to run up a private demo, so I found I could add auth_basic to the nginx config with the following configuration:

    webserver_virtualhosts:
      - hostname: "demo1.mycompany.com"
        default_server: yes
        extra: |
          auth_basic "Private Demo - please enter your credentials";
            auth_basic_user_file /etc/nginx/htpasswd;

Unfortunately, this doesn't work unless I also comment out [this line in the nginx role's host template](https://github.com/plone/ansible-playbook/blob/master/roles/nginx/templates/host.j2#L46).   I notice from the history of that file that `item.extra` used to be added after that line. Can we revert to that ordering?

**Comment by smcmahon** [comment]
I don't want to revert the ordering, as the change was intentional. But, it would be fine to add a location_extra setting that is explicitly targeted for the location section after the proxy_pass clause.

Will that work for you?

**Comment by djowett** [comment]
That would work for me.  But it's no trouble just to override it locally 
for now - as long as I'm not breaking anything
by commenting out your auth_basic line.



On 22/03/16 22:29, Steve McMahon wrote:
>
> I don't want to revert the ordering, as the change was intentional. 
> But, it would be fine to add a location_extra setting that is 
> explicitly targeted for the location section after the proxy_pass clause.
>
> Will that work for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/plone/ansible-playbook/issues/35#issuecomment-200061840>
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by djowett** [comment]
This fix doesn't work for me unfortunately.  I get the following in nginx.

> 2016/07/19 17:29:33 [emerg] 31936#0: "auth_basic" directive duplicate in /etc/nginx/sites-enabled/http_demob_jowettenterprises_com:20

The following works for me, and gets the indentation a little better, but testing for 'auth_basic ' like this seems wrong, what do you think??

    [...]
      location / {
    {%     if 'auth_basic ' not in item.get('location_extra', '') %}
        auth_basic off;
    {%     endif %}
    {%     if item.get('location_extra') != None %}
      {{     item.location_extra }}
    {%     endif %}
        rewrite ^/(.*)$ /VirtualHostBase/$vh_protocol/$server_name:$vh_port{{ item.zodb_path }}/VirtualHostRoot/$1 break;
        proxy_pass http://localhost:{{ proxycache_port|default('6081') }};
      }
    [...]

**Comment by djowett** [comment]
This fix doesn't work for me unfortunately.  I get the following in nginx.

> 2016/07/19 17:29:33 [emerg] 31936#0: "auth_basic" directive duplicate in /etc/nginx/sites-enabled/http_demob_jowettenterprises_com:20

The following works for me, and gets the indentation a little better, but testing for 'auth_basic ' like this seems wrong, what do you think??

    [...]
      location / {
    {%     if 'auth_basic ' not in item.get('location_extra', '') %}
        auth_basic off;
    {%     endif %}
    {%     if item.get('location_extra') != None %}
      {{     item.location_extra }}
    {%     endif %}
        rewrite ^/(.*)$ /VirtualHostBase/$vh_protocol/$server_name:$vh_port{{ item.zodb_path }}/VirtualHostRoot/$1 break;
        proxy_pass http://localhost:{{ proxycache_port|default('6081') }};
      }
    [...]

**Comment by djowett** [comment]
@smcmahon suggested fix in 3c12e3897, but it seems a bit hacky, so if you want to declare this a "wontfix", I'm not troubled by that!

**Comment by smcmahon** [comment]
The finer parts of the virtual hosting are all going to be hacks. We just need the right ones ;)
