### ISSUE TITLE
MOTD has some details wrong on multi-server

### ISSUE THREAD

**Issue by djowett** [plone/ansible-playbook#38]
This is whilst being test-deployed to Varnish,  MOTD shows the below (some details changed for confidentiality).

    Custom Services/Ports
    aclient: /usr/local/plone-5.0/aclient
        /AClient: demo1.jowettenterprises.com []
        zeo server: 127.0.0.1:8100
        zeo clients: 127.0.0.1:8081 
    bclient: /usr/local/plone-5.0/aclient
        /Plone: demo2.jowettenterprises.com []
        zeo server: 127.0.0.1:7100
        zeo clients: 127.0.0.1:8081 
    varnish: 127.0.0.1:6081
    varnish admin: 127.0.0.1:6082
    postfix: 25 (host-only)

The issues with the above are:

1. bclient: /usr/local/plone-5.0/aclient   - should show bclient at the end!
2. neither deployment is plone-5.0 - aclient is plone 4.3.2, bclient is plone 4.3.8
3. zeo client for bclient should have port number 7081

The plone servers seem to be working correctly, so I believe this is just an issue with motd

**Comment by djowett** [comment]
@smcmahon sorry this is not totally fixed (though it is better).

I still see an incorrect version for a plone 4.3 site, e.g.

    Custom Services/Ports
    aclient: /usr/local/plone-5.0/aclient

I'm a bit stumped as to how to fix this - though it is only cosmetic as far as I can see, and therefore low priority

**Comment by djowett** [comment]
Ok, fixed it for my case at least.  

The problem seems to stem from me *not* setting 

    plone_major_version: '4.3'

outside of `playbook_plones` - I've set it now & MOTD looks fine.

I had thought that `plone_major_version` would be calculated correctly from `plone_version` in `playbook_plones`, but that is obviously not the case.

@smcmahon any thoughts? I don't know whether you think of this as a user error :-) or a bug.  Close this if you like!

**Comment by smcmahon** [comment]
I'm unable to reproduce this. The major version should be deduced from the minor version. You should not have to set it. There was a bug in that at one point, but it got fixed. Any chance you updated?

**Comment by djowett** [comment]
@smcmahon I can't reproduce this either now, and I haven't yet taken any commits since f609dadc either.  I did wonder if it might have been because I had `plone_version: 4.3.8` rather than `plone_version: '4.3.8'` but that doesn't reproduce the problem.  

I'm more than happy to leave this closed - maybe someone in the same straights will find this issue one day!
