### ISSUE TITLE
Compile your own python?

### ISSUE THREAD

**Issue by gforcada** [plone/ansible-playbook#45]
Would it be interesting to allow users to compile their own python?

I created such an ansible role just for that: https://galaxy.ansible.com/gforcada/compile-python/

**Comment by smcmahon** [comment]
I believe the playbook supports this by allowing an override of the Python path. I prefer not to add the role in the interests of keeping things simple. Folks who need it may add the role and put it in their playbook or run it separately.

And, let's hope the Xenial python gets fixed soon.
