### ISSUE TITLE
Bring nginx SSL settings up to tightest reasonable

### ISSUE THREAD

**Issue by smcmahon** [plone/ansible-playbook#54]
Would be nice to score SSL labs A+

**Comment by tkimnguyen** [comment]
See https://www.ssllabs.com/ssltest/analyze.html?d=www.conversaafiada.com.br vs https://www.ssllabs.com/ssltest/analyze.html?d=2017.ploneconf.org

**Comment by smcmahon** [comment]
Diff between A and A+ is HSTS. And I don't think we want to force that out of the box. "A" is good enough for ootb config.

**Comment by smcmahon** [comment]
Completed in 1.2.16
