### ISSUE TITLE
centos7 buildout fails with error "ImportError: No module named six.moves"

### ISSUE THREAD

**Issue by cjsteel** [plone/ansible-playbook#71]
On Centos7 the default virtualenv does not include the following three pip installable packages which are installed by default on other versions of Ubuntu and Centos when creating a new virtualenv:

* six
* appdirs
* packaging

Running:
```shell
sudo -u plone_buildout /usr/local/plone-5.0/zeoserver/bin/pip freeze
```
shows these packages are missing on the default Centos7 installation.

output example:

```shell
wsgiref==0.1.2
```
Manual fix, log into the server and:

```shell
sudo -u plone_buildout /usr/local/plone-5.0/zeoserver/bin/pip install six
sudo -u plone_buildout /usr/local/plone-5.0/zeoserver/bin/pip install appdirs
sudo -u plone_buildout /usr/local/plone-5.0/zeoserver/bin/pip install packaging
```

check your work:

```shell
sudo -u plone_buildout /usr/local/plone-5.0/zeoserver/bin/pip freeze
```
Output example after fix (and successful playbook rerun):

```shell
appdirs==1.4.3
packaging==16.8
pyparsing==2.2.0
six==1.10.0
wsgiref==0.1.2
zc.buildout==2.9.3
```
Similar / same? issue: https://github.com/pypa/setuptools/issues/942

**Comment by smcmahon** [comment]
Sorry for not getting to this earlier. This does not cause a problem with the playbook, as one of the first things the plone server role does on RedHat family machines is update pip, virtualenv and setuptools.
