### ISSUE TITLE
Docs: web server virtual hosting and certificates sections are inconsistent

### ISSUE THREAD

**Issue by stevepiercy** [plone/ansible-playbook#73]
I noticed this because I'm muddling through how to use Let's Encrypt for secure certificates and auto-renewal in a cron job together with this project, as mentioned in #61.

In the documentation, from the note under [Virtual hosting setup](http://plone-ansible-playbook.readthedocs.io/en/latest/webserver.html#virtual-hosting-setup):

> If you are setting up an https server, you must supply certificate and key files. The files will be copied from your local machine (the one containing the playbook) to the target server.

Then in the next section, [Certificates](http://plone-ansible-playbook.readthedocs.io/en/latest/webserver.html#certificates):

> To use files that already exist on the controlled server, use:

I think these two items inconsistent. If you agree, I volunteer to provide the text in a PR.

**Comment by stevepiercy** [comment]
That helps, but did not address the issue. If the files already exist on the controlled server, then they will not be copied from your local machine (the one containing the playbook) to the target server. Or do I misunderstand?

**Comment by ramiroluz** [comment]
From the documentation you linked I understood that the keys will not be copied  if you chose to use keys that are already on the controlled machine.

**Comment by stevepiercy** [comment]
There's still a conflict between the note and Certificates section.

The note still says:

> The files will be copied from your local machine (the one containing the playbook) to the target server.

but the Certificates section says:

> Certificate files may be specified in one of two ways.
> ...
> To use files that already exist on the controlled server, use:

I'll submit a PR with a suggested improvement for cohesiveness.
