### ISSUE TITLE
Plone and Ubuntu version support

### ISSUE THREAD

**Issue by stevepiercy** [plone/ansible-playbook#78]
First of all, thank you for this phenomenal project!

I was able to run the playbook to install Plone 5.0.7 on Ubuntu Xenial 16.04 LTS in Vagrant on macOS Sierra. :tada:

I noticed a couple of possible updates, but I wanted to check with you before submitting a PR.

1. In [README.rst](https://github.com/plone/ansible-playbook/blame/master/README.rst#L33), is Ubuntu Xenial out of "development" status and now officially supported?
2. Ditto for [docs/intro.rst](https://github.com/plone/ansible-playbook/blame/9ea91b30ba406d0fd951cf7c1d4e33dfd1349eee/docs/intro.rst#L22)?
3. Bump [Plone version in samples](https://github.com/plone/ansible-playbook/commit/bb4af1deca4e4f6bad070e5c61e13f4ef8523a9c)?

**Comment by smcmahon** [comment]
The Xenial support is solid with 1.2.16. Docs updated. Thanks!

**Comment by stevepiercy** [comment]
Thank you, but you did not address item 3. Should the Plone version be bumped to 5.0.7 in the samples?

**Comment by nturner** [comment]
The docs at https://docs.plone.org/external/ansible-playbook/docs/intro.html still say that Ubuntu 16.04 LTS is not supported.

**Comment by stevepiercy** [comment]
@nturner thanks for the report. I just [submitted an issue to that repo](https://github.com/plone/documentation/issues/886).These docs get pulled in by the Plone documentation repo, but I don't know the details of how it works or why it is not current. Meanwhile there is a [current published version on RTD](http://plone-ansible-playbook.readthedocs.io/en/latest/).
