### ISSUE TITLE
Ubuntu 16.04 requires Python 2

### ISSUE THREAD

**Issue by stevepiercy** [plone/ansible-playbook#82]
Ubuntu 16.04 requires Python 2 installed for this playbook to run.

On Digital Ocean, I did the following:
* create a droplet of Ubuntu 16.04.2 x32
* add a new user for sudo and SSH
* followed the docs to set up the playbook
* issued following command with response:

```bash
(ansible_work) Steves-iMac:ansible-playbook stevepiercy$ ansible XXX.stevepiercy.us -a "whoami"
XXX.stevepiercy.us | FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Shared connection to ###.###.###.### closed.\r\n",
    "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

A quick search led me to [SO posts a-plenty](http://stackoverflow.com/questions/32429259/ansible-fails-with-bin-sh-1-usr-bin-python-not-found), but I couldn't decide which looked the best for automation. Instead I just installed Python 2 via SSH with `sudo apt-get install python-simplejson`. Now the command works:

```bash
(ansible_work) Steves-iMac:ansible-playbook stevepiercy$ ansible XXX.stevepiercy.us -a "whoami"
XXX.stevepiercy.us | SUCCESS | rc=0 >>
spiercy
```

I hang my head in shame for not automating gooder.

I also saw an issue in the tracker that mentioned this, and it seems that it got overlooked in the subsequent PRs.
https://github.com/plone/ansible-playbook/issues/16
https://github.com/plone/ansible-playbook/pull/17
https://github.com/plone/ansible-playbook/pull/43

**Comment by stevepiercy** [comment]
Thank you!

**Comment by mmorejon** [comment]
Once installed `python-simplejson`, ansible worked perfectly! 
Thank you!

**Comment by tkimnguyen** [comment]
as per https://github.com/plone/ansible-playbook/commit/9499e4b8039f5573bc163ddbe8adee32ad67dee9 indeed 

    which python2.7

then

    sudo apt-get install -y python

made my old plone.io branch work again :) thx @smcmahon (and @stevepiercy for filing the bug that I was looking for!)

**Comment by emmanuelstroem** [comment]
Because Ubuntu 16.04 and above come with python3,
you need to first set the python3 path in your hosts file like this:
`ansible_python_interpreter=/usr/bin/python3` 
for the initial  run of the playbook to install `python-simplejson` which installs python2 or just python.
