### ISSUE TITLE
Update for roles/plone.plone_server/templates/buildout.cfg.j2 needed?

### ISSUE THREAD

**Issue by stevepiercy** [plone/ansible-playbook#92]
In lines 51-53:

```jinja2
{% if instance_config.plone_version | version_compare('5.0.6', '<=') %}
    Products.PloneHotfix20160830
{% endif %}
```

I'm not sure how to update this. There is a [newer hotfix for 5.0.6](https://plone.org/security/hotfix/20170117), but I don't know whether to stack the hotfixes or replace them.

Also should there be a stanza for 5.0.7? 5.0.7 includes the hotfix, so I don't think it does.

**Comment by smcmahon** [comment]
Resolved when we did the 5.0.9 update 3 months ago.
