### ISSUE TITLE
audit task error when plone_instance_name is not defined.

### ISSUE THREAD

**Issue by ramiroluz** [plone/ansible-playbook#96]
Similar to issue #94.

When the file local-configure.yml don't define a plone_instance_name an error occur during the
template processing.

host os: debian jessie.
guest os: ubuntu xenial (also on debian jessie)

ansible --version
ansible 2.3.1.0
config file =
configured module search path = Default w/o overrides
python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

https://github.com/plone/ansible-playbook/blob/master/roles/audit/filter_plugins/audit_plugins.py#L41

TASK [audit : set_fact] **********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'plone_instance_name'
fatal: [xenial]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

**Comment by smcmahon** [comment]
Fixed long ago by https://github.com/plone/ansible-playbook/commit/cc38cd78ed830fd1a8128afd2a4cdcd18df90b2f#diff-b78aa49db2942da701c4e775ed7e31b8
